README.md
A little fix for the README example after testing this exporter in a docker container with a linked mysql one.
I was getting this error :
```
Default addr for network 'bdd' unknown
```
When using this `DATA_SOURCE_NAME`
```
login:password@bdd/dbname
```
The right way was :
```
login:password@(bdd:3306)/dbname
```
=> Fix DATA_SOURCE_NAME building and running example

mysqld_exporter.go
Fixes slave status parsing.  As it supports variable column widths, this should work on all 5.x versions of mysql/mariadb.  No promises about 4.x.
Also cleaned up log files - removing an extraneous space between description and error.
=> Fix slave status parsing

mysqld_exporter.go
Bugfix: Fix regex pattern, so that it no longer catches anything other than logs.
This got through all the testing we did here somehow.  Sorry about that.
=> Fix regex bug that caused numbers to be truncated.

Dockerfile, Makefile.COMMON, README.md, mysqld_exporter.go
Following the docker related PR series.
New Dockerfile using the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild) base image whose goal is to unified the way to dockerize prometheus tools and exporters based on Golang.
The binary is build using make. (Golang is installed via make too, respecting the GO_VERSION).
A testable image is available under my name on Docker hub : [Link](https://registry.hub.docker.com/u/sdurrheimer/mysqld-exporter/)
I have also added some Docker usage instructions in the readme.
As always, the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild)  image can be also move under Prometheus organization.
@juliusv @discordianfish
=> New Dockerfile using alpine-golang-make-onbuild base image

mysqld_exporter.go
Avoid miss-matched string case.
=> Make global status key always lower case

mysqld_exporter.go
This commit adds support for dumping Percona userstats. These metrics are per
user counters are are exported as such to enable detection of resets by
Prometheus.
The new functionality, being limited to Percona, is enabled by invoking with
-collector.userstats=true
=> Add support for Percona userstats output.

mysqld_exporter.go
Read metrics from performance_schema.events_statements_summary_by_digest
* Limit to the top digests by count (default to 250)
* Disabled by default becuase it can produce a large number of metrics
=> Add metrics for events statements by digest

mysqld_exporter.go
Refactoring the pointer dancing done in the userstats module led to a regression which broke collecting these statistics at all. This commit has been tested and fixes the issue.
=> Fix regression that broke userstats

mysqld_exporter.go
A few more cases where performance counters are returned as uint64
=> Update more mysql uint64 results

mysqld_exporter.go
Gather counter and time metrics from
`performance_schema.table_lock_waits_summary_by_table`[0]
Separate out SQL and External locks
[0]: https://dev.mysql.com/doc/refman/5.6/en/table-waits-summary-tables.html#table-lock-waits-summary-by-table-table
=> Add metrics for table locks

README.md, mysqld_exporter.go
SHOW MASTER LOGS or SHOW BINARY LOGS can be used to retrieve a
list of all binary logs (including size). Summing up the sizes
gives a rough counter for the current binlog size.
See https://dev.mysql.com/doc/refman/5.7/en/show-binary-logs.html
for details.
This gauge simply sums the File_size column. (Note that the total size will grow/shrink as new binlogs are written and old ones are purged)
Required mysql permission: SUPER or REPLICATION CLIENT
=> Add a collect.binlog_size flag that enables an aggregated binlog size gauge

README.md, mysqld_exporter.go
The new processlist flag enables "SHOW PROCESSLIST" and will generate a
simple connection counter that can be drilled down based on
- user
- source host
- query status / connection state
This is useful to find out more about concurrency problems
of a server (e.g. connection piling up, certain clients making
excessive use of lock, .....)
This is my first attempt at golang & prometheus. Expect some extra bugs and please give me some extra pointers to docs if anything is completely insane.
=> Add SHOW PROCESSLIST based counters

README.md, mysqld_exporter.go
Reduce the number of flags needed to enable performance_schema metrics.
* Reduces the number of flags needed to enable collection
* Reduces the number of queries to the server per collection
* Update README
Also fix typo in events_statements flag documentation
=> Consolidate performance_schema metrics flags

README.md, mysqld_exporter.go
Add two new `performance_schema` metrics tables:
* `events_waits_summary_global_by_event_name`[0]
* `file_summary_by_event_name`[1]
From https://github.com/prometheus/mysqld_exporter/issues/47
[0]: https://dev.mysql.com/doc/refman/5.6/en/wait-summary-tables.html
[1]: https://dev.mysql.com/doc/refman/5.6/en/file-summary-tables.html
=> Add new metrics

mysqld_exporter.go
Simplify `events_statements_summary_by_digest` `digest_text` by
including the text label in all metrics.  Since the digest and
digest_text are 1:1 there is no need to separate the text out.
=> Simplify `digest_text`

README.md
With the simplified digest_text labels this section no longer applies.
Also nothing else worth replacing this with comes to mind.
@SuperQ
=> Remove example query section

README.md, mysqld_exporter.go
Collect metrics from information_schema.tables
* Allow filtered list of databases to avoid performance problems on
MySQL < 5.6
* Default to all databases
* Include extra labels in `table_version`, useful for detecting crashed
tables `{engine="NONE"}`
=> Add metrics from information_schema.tables

README.md, mysqld_exporter.go
Added collecting of table stats (information_schema.TABLE_STATISTICS) similar to the existing user stats (information_schema.USER_STATISTICS).
Docs https://www.percona.com/doc/percona-server/5.5/diagnostics/user_stats.html#TABLE_STATISTICS Also the option `userstat` presents in MariaDB.
This allows to get the metrics of how many rows read/changed in the tables to find busiest or unused tables.
```
mysql_info_schema_table_statistics_rows_changed_total{schema="test",table="checksums"} 77
mysql_info_schema_table_statistics_rows_changed_total{schema="test",table="heartbeat"} 0
mysql_info_schema_table_statistics_rows_changed_x_indexes_total{schema="test",table="checksums"} 154
mysql_info_schema_table_statistics_rows_changed_x_indexes_total{schema="test",table="heartbeat"} 0 …
```
=> Added collecting of table statistics

mysqld_exporter.go
It would be great to display MySQL version and distribution on the dashboards having a simple metric to report this, similar to `node_uname_info` from node_exporter.
When the existing option `-collect.global_variables` is enabled, it will create the following metric:
```
mysql_version_info{version="5.5.44",version_comment="Source distribution"} 1
```
=> Create mysql_version_info metric to report MySQL version and distro

mysqld_exporter.go
Compiling with default settings I got:
./mysqld_exporter.go:748: too many arguments to return
=> Fixing the return of the function and logging the error

mysqld_exporter.go
SHOW GLOBAL STATUS Handler_.* is similar to Com_.*
Aggregate the handlers into a single metric with labels for the various
handler types.
=> Add labels to global status "handlers" counters

mysqld_exporter.go
`SHOW BINARY LOGS` unlike other SQL queries produces the error when `log-bin` is OFF:
```
INFO[0000] Error scraping binlog size: Error 1381: You are not using binary logging  file=mysqld_exporter.go line=797
```
This causes all other scrapes coming after `scrapeBinlogSize()` to not execute, in particular all `scrapePerf*` ones. Added a check that prevents running this query when `log_bin` if OFF.
=> Check log_bin before running SHOW BINARY LOGS

README.md, mysqld_exporter.go
Adding support for reading MySQL credentials from `.my.cnf`. Using environmental variable to pass the DSN is not really flexible from automation point of view.
=> Added .my.cnf support

README.md, mysqld_exporter.go
https://www.percona.com/doc/percona-server/5.6/diagnostics/response_time_distribution.html
https://mariadb.com/kb/en/mariadb/query_response_time-plugin/
Sample:
```
mysql_info_schema_query_response_time_count_bucket{le="1e-06"} 281
mysql_info_schema_query_response_time_count_bucket{le="1e-05"} 756
mysql_info_schema_query_response_time_count_bucket{le="0.0001"} 8410
mysql_info_schema_query_response_time_count_bucket{le="0.001"} 11247
mysql_info_schema_query_response_time_count_bucket{le="0.01"} 11904
mysql_info_schema_query_response_time_count_bucket{le="0.1"} 11916
mysql_info_schema_query_response_time_count_bucket{le="1"} 11917
mysql_info_schema_query_response_time_count_bucket{le="10"} 11917
mysql_info_schema_query_response_time_count_bucket{le="100"} 11917 …
```
=> Added query response time distribution

README.md, mysqld_exporter.go
Add metrics from information_schema.innodb_metrics.
* Ignore `status_counter` metrics duplicatd by `SHOW GLOBAL STATUS`
* Only show enabled metrics.
=> Add metrics from information_schema.innodb_metrics

mysqld_exporter.go
Use correct type exposed by the `information_schema.innodb_metrics` table.
* Work around issues where some counters return negative numbers.
It turns out that MySQL is inconsistent in which metrics are in `SHOW
GLOBAL STATUS` and which are in `information_schema.innodb_metrics`.
* Include all `status_counter` metrics as counters.
=> Fix innodb_metrics collector

mysqld_exporter.go
For large enough values, MySQL returns exponential notation from
`POW()`.  The metric value is a float64 anyway, so we can fix this
mismatch by parsing this as a float in the first place.
@SuperQ
=> Parse auto increment values and maximum as float64.

mysqld_exporter_test.go
Added a first test for one fuction as PoC of SQL mocking. Besides checking the counters and histogram it also ensures the function executes exactly the queries expected.
Feel free to update as you wish.
```
$ go test -race -v
=== RUN   Test_scrapeQueryResponseTime
--- PASS: Test_scrapeQueryResponseTime (0.00s)
PASS
ok  	_/Users/weber/git/mysqld_exporter	1.032s
```
=> Added one test

mysqld_exporter.go
Add a simple `SELECT 1` query to always export a proxied up metric for
mysqld.
=> Add `mysql_up` metric

mysqld_exporter.go
go-database-sql keeps a stale connection open if the returned rows are not read or closed.
fixed id by calling .Close() on the result
https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/surprises.md#resource-exhaustion
=> The result of the upQuery should be read or closed

mysqld_exporter.go, mysqld_exporter_test.go
Added `SHOW ENGINE TOKUDB STATUS` metrics for Percona Server with TokuDB storage engine. Note, the metrics are set untyped (similar to `GLOBAL STATUS`) because this is a whole mess of different types.
```
mysql_engine_tokudb_num_open_dbs_now 0
mysql_engine_tokudb_period_in_ms_that_recovery_log_is_automatically_fsynced 0
mysql_engine_tokudb_txn_aborts 2
mysql_engine_tokudb_txn_begin 5
mysql_engine_tokudb_txn_begin_read_only 0
mysql_engine_tokudb_txn_successful_commits 3
```
~300
=> Added metrics from SHOW ENGINE TOKUDB STATUS

mysqld_exporter.go, mysqld_exporter_test.go
As reported by https://github.com/prometheus/mysqld_exporter/issues/96,
we do need to collect metrics for update and delete index IO waits.
=> Include index io stats for update and delete

mysqld_exporter.go
Standardize collector error messages
* Always use the name of collector flag in the error message to avoid confusion when looking at logs.
"DELAYED" Inserts were deprecated in MySQL 5.6.6[0].  These metrics
cause MySQL 5.7 scrapes to fail.
[0]: https://dev.mysql.com/doc/refman/5.6/en/table-waits-summary-tables.html
=> Fix scrape errors for MySQL 5.7

collector/info_schema_innodb_metrics.go, collector/info_schema_innodb_metrics_test.go
For information_schema.innodb_metrics we can split out labels based on
the type of buffer page IO operation in the "buffer_page_io" subsystem.
* Simplify scrapeInnodbMetrics() by casting value to float64.
=> Add special handling of "buffer_page_io" subsystem

README.md, mysqld_exporter.go
* Disable by default to avoid breaking with old MySQL versions
* Document flag as only compatible with >= 5.7
=> Fix collect.info_schema.innodb_tablespaces

collector/collector.go, collector/slave_status_test.go
Treat `SHOW SLAVE STATUS` "Slave_IO_Running" column status `Connecting`
as not running.
=> Fix SLAVE STATUS "Connecting"

collector/slave_status.go, collector/slave_status_test.go
For multi source replication `SHOW SLAVE STATUS` returns following output:
```csv
Slave_IO_State,Master_Host,Master_User,Master_Port,Connect_Retry,Master_Log_File,Read_Master_Log_Pos,Relay_Log_File,Relay_Log_Pos,Relay_Master_Log_File,Slave_IO_Running,Slave_SQL_Running,Replicate_Do_DB,Replicate_Ignore_DB,Replicate_Do_Table,Replicate_Ignore_Table,Replicate_Wild_Do_Table,Replicate_Wild_Ignore_Table,Last_Errno,Last_Error,Skip_Counter,Exec_Master_Log_Pos,Relay_Log_Space,Until_Condition,Until_Log_File,Until_Log_Pos,Master_SSL_Allowed,Master_SSL_CA_File,Master_SSL_CA_Path,Master_SSL_Cert,Master_SSL_Cipher,Master_SSL_Key,Seconds_Behind_Master,Master_SSL_Verify_Server_Cert,Last_IO_Errno,Last_IO_Error,Last_SQL_Errno,Last_SQL_Error,Replicate_Ignore_Server_Ids,Master_Server_Id,Master_UUID,Master_Info_ …
```
=> scrape slave status for multisource replication

mysqld_exporter.go
With this change we will get the consistent error logging messages:
```
$ cat mysqld_exporter.go |grep 'Error scraping'
log.Errorln("Error scraping for collect.global_status:", err)
log.Errorln("Error scraping for collect.global_variables:", err)
log.Errorln("Error scraping for collect.slave_status:", err)
log.Errorln("Error scraping for collect.info_schema.processlist:", err)
log.Errorln("Error scraping for collect.info_schema.tables:", err)
log.Errorln("Error scraping for collect.info_schema.innodb_sys_tablespaces:", err)
log.Errorln("Error scraping for collect.info_schema.innodb_metrics:", err)
log.Errorln("Error scraping for collect.auto_increment.columns:", err)
log.Errorln("Error scraping for collect.binlog_size:", err)
log.Errorln("Error scraping for …
```
=> Consistency of error logging.

collector/info_schema_innodb_metrics.go, collector/info_schema_innodb_metrics_test.go
Add label aggregation for innodb_metrics buffer subsystem.
* Total can be ignored as it is an aggregation of data+misc+free
* Dirty pages are not aggregateable, keep as a separate metric.
=> Add label aggregation for innodb buffer metrics

collector/binlog.go, collector/binlog_test.go
We have binlog count and total size, however it's impossible to measure how frequently the binlogs are rotated. The count does not tell this as it can be constantly on the same number.
I have added a new metric to expose what binlog file number currently is:
```
mysql_binlog_file_number 16
```
This stays for say `mysql-bin.000016`. The part after `.` is exposed as a value.
Also added the test.
=> Added the last binlog file number metric.

collector/global_status.go, collector/global_status_test.go, collector/global_variables.go, collector/global_variables_test.go
* Added `mysql_galera_status_info`, `mysql_galera_variables_info` metrics.
* Added global variables test.
```
mysql_galera_status_info{wsrep_cluster_state_uuid="6c06e583-686f-11e6-b9e3-8336ad58138c",wsrep_local_state_uuid="6c06e583-686f-11e6-b9e3-8336ad58138c",wsrep_provider_version="3.16(r5c765eb)"} 1
mysql_galera_variables_info{wsrep_cluster_name="supercluster"} 1
```
I didn't create another collector for those metrics as they are derived from the existing ones, whether `SHOW GLOBAL VARIABLES` or `SHOW GLOBAL STATUS` which are scraped usually anyway.
Also I think we don't need any other `wsrep_` vars, don't we?
```
mysql> show global variables where Variable_Name like 'wsrep%';
+---------------------------------+-----------------------------------------+
| Variable_name …
```
=> Added PXC/Galera info metrics.

README.md
MySQL 5.5 gives this error when `-collect.perf_schema.file_events` enabled:
```
collect.perf_schema.file_events: Error 1054: Unknown column 'SUM_TIMER_READ' in 'field list'"...
```
It is actually 5.6 focused, not sure there is a reason to support it in 5.5.
Let's fix this in README.
=> Updated MySQL version supported for -collect.perf_schema.file_events

README.md, collector/engine_innodb.go, collector/engine_innodb_test.go, mysqld_exporter.go
Parsed those 3 numbers from `SHOW ENGINE INNODB STATUS `
```
0 queries inside InnoDB, 0 queries in queue
0 read views open inside InnoDB
```
```
mysql_engine_innodb_queries_in_queue 0
mysql_engine_innodb_queries_inside_innodb 0
mysql_engine_innodb_read_views_open_inside_innodb 0
```
=> Added metrics from SHOW ENGINE INNODB STATUS.

collector/collector.go
Treat `SHOW GLOBAL STATUS like 'wsrep_cluster_status'`:
- `Primary` node is part of a operational component
- `Non-Primary`/`Disconnected ` the node is part of a nonoperational component
=> Fix wsrep_cluster_status

collector/info_schema_query_response_time.go, collector/info_schema_query_response_time_test.go
Adding read/write split to query response time distribution. Percona Server 5.6/5.7 supports that, PS 5.5 and MariaDB - only totals.
```
mysql_info_schema_query_response_time_seconds_bucket{le="1e-06"} 33758
mysql_info_schema_query_response_time_seconds_bucket{le="1e-05"} 97717
mysql_info_schema_query_response_time_seconds_bucket{le="0.0001"} 520449
mysql_info_schema_query_response_time_seconds_bucket{le="0.001"} 701573
mysql_info_schema_query_response_time_seconds_bucket{le="0.01"} 795705
mysql_info_schema_query_response_time_seconds_bucket{le="0.1"} 805960
mysql_info_schema_query_response_time_seconds_bucket{le="1"} 806175
mysql_info_schema_query_response_time_seconds_bucket{le="10"} 806175
mysql_info_schema_query_response_time_seconds_bucket{le="100"} 806175 …
```
=> Added read/write split to query response time distribution.

collector/global_variables.go, collector/global_variables_test.go
Added `gcache.size` as a metric from `wsrep_provider_options` global variable for PXC/Galera.
This is useful to compare with the rate of `sum(wsrep%bytes)` status variables to figure out how much time a node can be out of the cluster before it will require SST vs IST. [Details](http://severalnines.com/blog/how-avoid-sst-when-adding-new-node-galera-cluster)
=> Add mysql_galera_gcache_size_bytes metric.

README.md, collector/info_schema_query_response_time.go, mysqld_exporter.go
Improve [![Go Report Card](https://goreportcard.com/badge/github.com/prometheus/mysqld_exporter)](https://goreportcard.com/report/github.com/prometheus/mysqld_exporter)
=> Get 100% for golint and misspell of goreportcard 😎

collector/perf_schema_events_statements.go
Workaround bug reported by #127.
* Use a sub-select and group by to limit to one digest/schema pair.
=> Add workaround for MySQL bug

collector/slave_status.go, collector/slave_status_test.go
The syntax differs between MySQL/Percona and MariaDB for the multi source replication.
The `SHOW SLAVE STATUS` is `SHOW ALL SLAVES STATUS` and the `Channel_name` is `Connection_name`.
Cheers,
Max.
=> Add MariaDB multi source replication support

README.md, collector/heartbeat.go, collector/heartbeat_test.go, collector/slave_status.go, mysqld_exporter.go
pt-heartbeat measures actual replication lab on a mysql server. It does
not rely on data stored in SHOW SLAVE STATUS, as it can be unreliable.
pt-heartbeat website:
https://www.percona.com/doc/percona-toolkit/2.2/pt-heartbeat.html
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Implement heartbeat metrics

collector/info_schema_clientstats_test.go, collector/info_schema_userstats_test.go
See also the build failures for i386 at https://buildd.debian.org/status/package.php?p=prometheus-mysqld-exporter#problem-3
The fix is trivial but I was surprised it happened at all since mysqld_exporter is already built/released for i386 by promu. Any idea why this was the case?
=> collector: fix 32bit int overflow in tests

example.rules
Heartbeat[0] metrics allow for similar alerting symantics to "seconds
behind master" metrics.
* Add a recording rule to provide a similar gauge of seconds behind.
* Add an alert with the same style.
[0]: https://github.com/prometheus/mysqld_exporter/pull/183
=> Add an example of heartbeat metrics for slave lag

README.md, collector/perf_schema_file_instances.go, collector/perf_schema_file_instances_test.go, mysqld_exporter.go
This adds MySQL 5.5 compatible file access metrics. It might be related to #126.
I needed this to monitor table access in MySQL 5.5 where newer performance_schema tables are not present.
It could be enabled with:
-collect.perf_schema.file_instances
The emitted metrics per file are (example):
mysql_perf_schema_file_instances_bytes{file_name="table.MYD",mode="read"} 244
mysql_perf_schema_file_instances_bytes{file_name="table.MYD",mode="write"} 0
mysql_perf_schema_file_instances_total{file_name="table.MYD",mode="read"} 4
mysql_perf_schema_file_instances_total{file_name="table.MYD",mode="write"} 0
Filtering 'file_name' is possible via a regexp to restrict the number of emitted metrics:
-collect.perf_schema.file_instances.filter=basedir/.*(MYD|MYI)
The path-prefix of the 'file_name' label is …
=> Add basic file_summary_by_instance metrics

example.rules
Add a recording rule example for "Transactions Per Second".
[0]: https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_transaction
Closes: https://github.com/prometheus/mysqld_exporter/issues/198
=> Add a recording rule example for TPS

mysqld_exporter.go
I'm trying to hunt down some leaking connection issues. While this doesn't nail the issue it's something I was surprised not to see in exporter.
If user forgets to limit number of connections from db perspective, we still won't create hundreds of them. Even if user sets `MAX_USER_CONNECTIONS 3` then golang driver won't even try to create new connection.
Also `SetConnMaxLifetime` gets rid of idle and stale/broken connections.
Let me know what you think.
https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns
https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns
https://github.com/golang/go/commit/0c516c16328575ab78a4cce49874955dd590efa2
=> Limit number and lifetime of connections

collector/perf_schema_file_instances.go, collector/perf_schema_file_instances_test.go
Include the event name column as a label for metrics gathered from `performance_schema.file_summary_by_instance`.
Default to not cleaning the path on `performance_schema.file_summary_by_instance`
names to avoid name colisions.
Closes: https://github.com/prometheus/mysqld_exporter/issues/203
=> Fix file_instances metric collector

collector/exporter.go, collector/heartbeat.go, collector/heartbeat_test.go, mysqld_exporter.go
This decouples collector implementation from http server and cli client.
This way I can create my own binary with several collectors by using `collector.New`.
All scrappers were already in `/collector` subpackage, so I just moved `Exporter` struct which is implementation of prometheus `Collector`, also to `/collector` subpackage.
=> Move Exporter to /collector so it can be used as a library

README.md, mysqld_exporter.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go, vendor/vendor.json
As discussed on #234 and IRC, this PR adds a `collect` URL parameter to filter currently enabled collectors.
Closes: https://github.com/prometheus/mysqld_exporter/issues/234
=> Add 'collect' URL parameter to filter enabled collectors

collector/exporter.go
=> Set last_scrape_error when an error occurs

collector/exporter.go
Set a session level `lock_wait_timeout` to avoid stuck metadata locks.
Closes: https://github.com/prometheus/mysqld_exporter/issues/167
=> Set a lock_wait_timeout on the MySQL connection

Makefile
github.com/prometheus/client_golang says:
This library requires Go1.7 or later.
=> drop support go1.5

README.md, collector/exporter.go, mysqld_exporter.go
In order to avoid lost session params if the `db` object reconnects in
the background, move session params to the DSN string configuration.
=> Move session params to DSN

collector/perf_schema_file_instances_test.go, mysqld_exporter.go, mysqld_exporter_test.go
`landingPage` variable (which includes `*metricPath` flag) can't be defined until `kingpin.Parse()` is called. Otherwise we end up with empty `href`.
```
<html>
<head><title>MySQLd exporter</title></head>
<body>
<h1>MySQLd exporter</h1>
<p><a href=''>Metrics</a></p>
</body>
</html>
```
=> Broken landing page, doesn't include metric path.

collector/global_variables_test.go
Be explicit about 64bit int in test.
Closes: https://github.com/prometheus/mysqld_exporter/issues/272
=> Fix 32bit compile issue

README.md, collector/slave_hosts.go, collector/slave_hosts_test.go, mysqld_exporter.go, vendor/github.com/satori/go.uuid/LICENSE, vendor/github.com/satori/go.uuid/README.md, vendor/github.com/satori/go.uuid/codec.go, vendor/github.com/satori/go.uuid/generator.go, vendor/github.com/satori/go.uuid/sql.go, vendor/github.com/satori/go.uuid/uuid.go, vendor/vendor.json
Closes: #267
Adds a new sub system to show data about the output of `SHOW SLAVE HOSTS`. This  command shows currently running slaves from the master, however it can be presented in two seperate formats;
This is from an old version of MySQL
```
mysql> SHOW SLAVE HOSTS;
+-----------+----------------------------+------+-------------------+-----------+
| Server_id | Host                       | Port | Rpl_recovery_rank | Master_id |
+-----------+----------------------------+------+-------------------+-----------+
| 380239978 | backup_server_1 |    0 |                 0 |         1 | 
|  11882498 | backup_server_2 |    0 |                 0 |         1 | 
+-----------+----------------------------+------+-------------------+-----------+
3 rows in set (0.00 sec)
```
This is from a new version of …
=> Add metrics for the output of "SHOW SLAVE HOSTS"

mysqld_exporter.go, mysqld_exporter_test.go
Below is valid MySQL config however mysqld_exporter fails to read it,
because of the boolean keys.
Config:
```
[client]
user = root
password = abc123
[mysql]
skip-auto-rehash
```
For reference: https://jira.percona.com/browse/PMM-2469
=> Ignore boolean keys in my.cnf.

collector/exporter.go, collector/exporter_test.go, mysqld_exporter.go
There are two issues with scrapping I would like to address:
* `mysql_exporter_scrapes_total` never increases
```
$ curl --silent localhost:9104/metrics | grep scrapes_total | grep -v '#'
mysql_exporter_scrapes_total 2
$ curl --silent localhost:9104/metrics | grep scrapes_total | grep -v '#'
mysql_exporter_scrapes_total 2
$ curl --silent localhost:9104/metrics | grep scrapes_total | grep -v '#'
mysql_exporter_scrapes_total 2
```
https://github.com/prometheus/mysqld_exporter/pull/235#discussion_r173890280
* `mysqld_exporter` every request scrapes source database twice - this means double load for MySQL database itself. The scrape is done twice because `Describe()` also runs `Collect()`. Additionally, every request we register new collector so every request we call `Describe()` and …
=> PMM-2612: Scrape MySQL database only once and fix scrape counter.

collector/exporter.go
I know it's trivial :P But I'm curious why not use native `DB.Ping()` instead of in-house implementation? It should also avoid generating unnecessary `SELECT 1` statements.
=> Use native DB.Ping() instead of self-written implementation

README.md, mysqld_exporter.go
Per discussion in #226, there is no way to specify a custom CA that the
mysqld exporter will trust when establishing a SSL connection to a mysql
server. So if a mysql server has a custom truststore, an operator would
need to set DSN, where tls=skip-verify.
With this change, a user can define the ssl options in the mysql cnf and
then the mysqld exporter will construct a DSN and a custom TLS config
based on those options.
=> Support custom CA truststore and client SSL keypair.

.circleci/config.yml
Update based on the latest upstream prometheus circleci config.
=> Update circleci build

README.md
Update the `collect[]` param documentation to match the `node_exporter`
docs. This avoids new user copy-pasta issues.
=> Update collect[] param documentation

CHANGELOG.md
Fix typo of `collect` flag example in the CHANGELOG.
Fixes: https://github.com/prometheus/mysqld_exporter/issues/312
=> Fix flag name in CHANGELOG

collector/global_variables.go
> "mysql_global_variables_validate_password.check_user_name" is not a valid metric name
* replace `.` with `_`
```
2018/05/21 20:04:06 http: panic serving 10.10.11.50:59840: descriptor Desc{fqName: "mysql_global_variables_validate_password.check_user_name", help: "Generic gauge metric from SHOW GLOBAL VARIABLES.", constLabels: {}, variableLabels: []} is invalid: "mysql_global_variables_validate_password.check_user_name" is not a valid metric name
goroutine 295 [running]:
net/http.(*conn).serve.func1(0xc42007c140)
/usr/lib/golang/src/net/http/server.go:1697 +0xd0
panic(0x82f6c0, 0xc4205db530)
/usr/lib/golang/src/runtime/panic.go:491 +0x283
github.com/percona/mysqld_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc420135880, 0xc42004db58, 0x1, 0x1) …
```
=> PMM-2576: Fix prometheus metric names for SHOW GLOBAL VARIABLES.

collector/collector.go
@SuperQ 
In mysql 5.7.22 we encountered an issue where the entire process would completely lock up. We were able to solve it by modifying this one file and also removing the '--collect.binlog_size' param from the mysqld exporter.
Here is the bug report: https://bugs.mysql.com/bug.php?id=92108
=> Use GLOBAL to prevent mysql deadlock

CHANGELOG.md, collector/info_schema_processlist.go, mysqld_exporter.go
Added 2 new flags --collect.info_schema.processlist.processes_by_user and --collect.info_schema.processlist.processes_by_host which are needed in addition to --collect.info_schema.processlist.
By using them you get 2 new metrics:
- mysql_info_schema_processes_by_user{src_user=""}
- mysql_info_schema_processes_by_host{src_host=""}
Found it very useful to have this metrics and thought it could be interesting to have it in place for many people.
Closes: https://github.com/prometheus/mysqld_exporter/issues/334
=> add metrics to monitor processes by user and host

collector/global_status.go, collector/global_status_test.go
Apply `validPrometheusName()` to global status collector.
Closes: https://github.com/prometheus/mysqld_exporter/issues/325
=> Fix global status metric names

collector/global_variables.go, collector/global_variables_test.go
To make them more user-friendly.
Only RocksDB-specific metrics are included for now, but that map can (and will) be extended to include other variables.
=> Add help for some GLOBAL VARIABLES metrics.

collector/binlog.go, collector/engine_innodb.go, collector/engine_tokudb.go, collector/exporter.go, collector/exporter_test.go, collector/global_status.go, collector/global_variables.go, collector/heartbeat.go, collector/info_schema_auto_increment.go, collector/info_schema_clientstats.go, collector/info_schema_innodb_cmp.go, collector/info_schema_innodb_cmpmem.go, collector/info_schema_innodb_metrics.go, collector/info_schema_innodb_sys_tablespaces.go, collector/info_schema_processlist.go, collector/info_schema_query_response_time.go, collector/info_schema_tables.go, collector/info_schema_tablestats.go, collector/info_schema_userstats.go, collector/perf_schema_events_statements.go, collector/perf_schema_events_waits.go, collector/perf_schema_file_events.go, collector/perf_schema_file_instances.go, collector/perf_schema_index_io_waits.go, collector/perf_schema_replication_group_member_stats.go, collector/perf_schema_table_io_waits.go, collector/perf_schema_table_lock_waits.go, collector/scraper.go, collector/slave_hosts.go, collector/slave_status.go
=> Add minimal MySQL version to Scraper interface

CHANGELOG.md, README.md, collector/info_schema_schemastats.go, collector/info_schema_schemastats_test.go, mysqld_exporter.go
Adding a new collector to get the table stats info (if available) grouped by schema.
@SuperQ
=> Add collector to get table stats grouped by schema

CHANGELOG.md, collector/exporter.go
Clear last_scrape_error on every scrape, otherwise last_scrape_error
remains to be set to 1 despite the fact issue which has caused the error
in the first place is gone.
Fixes #367
=> Clear last_scrape_error on every scrape

.circleci/config.yml
This is a quick fix to unblock https://github.com/prometheus/mysqld_exporter/pull/387. `codespell` released a new version a few days ago that probably includes new checks.
=> Update codespell settings

mysqld_exporter.go
Note that the next release of client_golang will remove all deprecated
features.
Note that this _will_ change the metrics about the exposition itself.
=> Remove deprecated usage of prometheus/client_golang

README.md, collector/perf_schema_events_statements_sum.go, mysqld_exporter.go
This PR adds collector with aggregated perf_schema.eventstatements metrics (when it makes sense).
The reason why I did this is that we have a lot of MySQL servers with different SQL queries and multiplication X by Y gives us an enormous number of series. We would like to monitor this values still, but it requires either complex setup of Prometheus servers with the federation, either switching off this collector on most of the servers.
Having this collector enables allows us to have an overview of all performance events, and thanks to `collect[]` parameter feature easily enable extra verbose collector on problematic ones.
Basically, this code is copied and modified `collector/perf_schema_events_statements.go` one.
=> Add perf_schema.eventsstatementssum collector

CHANGELOG.md, mysqld_exporter.go
`info_schema.tables` has a danger of excessive cardinality, disable by
default.
Fixes: https://github.com/prometheus/mysqld_exporter/issues/401
=> Disable info_schema.tables collector by default

Dockerfile
`MAINTAINER` parameter is deprecated. `LABEL "key=value` must be used.
=> fixing deprecated MAINTAINER parameter

CHANGELOG.md, mysqld_exporter.go
This is useful in cases where the provided certs do not include hostname
information, such as GCP's SQL instances.
Closes #348
=> Add option to skip tls hostname verification

.travis.yml
No need to run the full test suite in Travis, this is handled by
CircleCI.
=> Only build in travis tests

README.md
As mentioned in #187, it makes sense to mention explicitly that this exporter supports MariaDB in addition to MySQL.
=> README.md: mention MariaDB

README.md, collector/info_schema_replica_host.go, collector/info_schema_replica_host_test.go, mysqld_exporter.go
This adds a collector for metrics in Amazon Aurora's information_schema.replica_host_status table, that are suitable for Prometheus:
mysql_info_schema_replica_host_cpu_percent The CPU usage as a percentage.
mysql_info_schema_replica_host_lag_seconds The replica lag in seconds.
mysql_info_schema_replica_host_log_stream_speed The log stream speed in kilobytes per second.
mysql_info_schema_replica_host_replay_latency_seconds The current replay latency in seconds.
mysql_info_schema_replica_host_slave_latency_seconds The master - slave latency in seconds.
=> Add collector for AWS Aurora information_schema.replica_host_status

CHANGELOG.md, README.md, collector/perf_schema_replication_group_members.go, collector/perf_schema_replication_group_members_test.go, mysqld_exporter.go
Fixes #362 
The scraper sends a new Gauge metric with a static value of 1 and labels corresponding to columns of the replication_group_members table. I made this choice because the labels are very much static - if there's an idea for something more elegant I'm quite happy to change it :relaxed: 
Both 5.7 and 8.0 are supported, by way of a different query for each. The first query sent is used to determine whether the additional columns present in the 8.0 schema are there, and falls back to the 5.7 schema.
Hope this makes sense..
=> Add collector for replication_group_members

README.md, collector/heartbeat.go, collector/heartbeat_test.go
`pt-heartbeat` supports UTC for heartbeat timestamps.
> The heartbeat table requires at least one row. If you manually create the heartbeat table, then you must insert a row by doing:
> 
> ```sql
> INSERT INTO heartbeat (ts, server_id) VALUES (NOW(), N);
> ```
> or if using `--utc`:
> ```sql
> INSERT INTO heartbeat (ts, server_id) VALUES (UTC_TIMESTAMP(), N);
> ```
https://www.percona.com/doc/percona-toolkit/LATEST/pt-heartbeat.html#cmdoption-pt-heartbeat-utc
When I started playing with `mysqld_exporter` I noticed 7200 second gap between heartbeat metrics. I understood that MySQL server was using the system timezone (https://time.is/CET), but the heartbeat timestamps were in UTC. 
This patch allows configuring the heartbeat collector to be consistent in such cases.
=> Support heartbeats in UTC

mysqld_exporter.go
The following codes always output 'msg="collect[] params" params="unsupported value type"'.
```
level.Debug(logger).Log("msg", "collect[] params", "params", params)
```
This "params" variable is slice, so should be split to string.
This is example log output by modified code.
```
msg="collect[] params" params=info_schema.innodb_cmp+nfo_schema.query_response_time
```
=> fix log output of collect[] params

CHANGELOG.md, README.md, collector/perf_schema_file_instances.go, collector/perf_schema_memory_events.go, collector/perf_schema_memory_events_test.go, go.sum, mysqld_exporter.go
This PR adds a collector for `performance_schema.memory_summary_global_by_event_name`, creating three metrics as described in #75 .
- The collector is disabled by default
- Include a flag to remove the `memory/` prefix from each event label for this metric.
- Tested locally against MySQL 5.6, 5.7 and 8.
- 5.6 doesn't have this table, so upon scrape, the exporter logs: 
```
level=error ts=2020-11-11T17:06:26.873Z caller=exporter.go:174 msg="Error from scraper" scraper=perf_schema.memory_events err="Error 1146: Table 'performance_schema.memory_summary_global_by_event_name' doesn't exist"
```
- Running against mysql:8 and mysql:5.7 with performance_schema=OFF, the exporter logs no errors and does not export any memory_events metrics, but does expose `mysql_exporter_collector_duration_seconds …
=> Feat add ps memory collector

collector/perf_schema_memory_events.go, collector/perf_schema_memory_events_test.go
Related to https://github.com/prometheus/mysqld_exporter/issues/75 and PR https://github.com/prometheus/mysqld_exporter/pull/515
It is possible to end up with a negative value for `CURRENT_NUMBER_OF_BYTES_USED` - this can happen if you enabled instrumentation for performance_schema memory at some point after startup time. 
Currently, if this is the case, the collector emits the following error when scraped, and stops scraping rows after the first row with a negative value for this column:
```
caller=exporter.go:174 msg="Error from scraper" scraper=perf_schema.memory_events err="sql: Scan error on column index 3, name \"CURRENT_NUMBER_OF_BYTES_USED\": converting driver.Value type []uint8 (\"-3214848\") to a uint64: invalid syntax"
```
This change makes the `currentBytes` variable signed, …
=> bugfix: allow perf_schema.memory summary current_bytes to be negative

README.md
The link to the docker-hub page was
https://registry.hub.docker.com/u/prom/mysqld-exporter/
This is an empty page so I changed it to
https://registry.hub.docker.com/r/prom/mysqld-exporter/
=> Update README.md - Fix docker-hub link

.circleci/config.yml, CHANGELOG.md, collector/collector.go
* Always lowercase strings to improve matching.
* Add match for "disabled" as false.
Fixes: https://github.com/prometheus/mysqld_exporter/issues/547
=> Improve parsing of boolean strings

collector/slave_hosts.go, collector/slave_hosts_test.go
Fixes https://github.com/prometheus/mysqld_exporter/issues/422
The `show slave hosts` command on mysql 5.5 and mariadb 10.5 returns neither a `Slave_UUID` nor a `Rpl_recovery_rank` column. Set the `slave_uuid` metric label to `""` in this case.
The unit test is copied from `TestScrapeSlaveHostsNewFormat`, with the mocked and expected rows amended. I also tested this with real MySQL 5.5.62, MySQL 5.7.33 and MariaDB 10.5.10 servers.
@SuperQ Can you please review this pull request? If I missed something, please let me know.
=> fix mysql_slave_hosts_info for mysql 5.5 and mariadb 10.5, add unit test

collector/info_schema_processlist.go, collector/info_schema_processlist_test.go
Hello,
Rewritten processlist collector to include both Command and State columns and stop doing state remapping.
Couple of reasons for this:
* The existing collector has been last updated 3 years ago when we had no MySQL 8.0. Since that time we have got more process states and changes to the existing ones https://dev.mysql.com/doc/refman/8.0/en/general-thread-states.html
The old re-mapping is not accurate, somewhat outdated and requires constant maintaining. With this PR, we won't bother about thread state mapping and it will flexible for anyone to do what they want to do on the expression side.
* The existing collector does incorrect grouping by Command/State. For example, anything Command=Query is considered as State=executing which may include:
```
{command="query", …
```
=> Rewrite processlist collector

collector/global_variables.go, collector/global_variables_test.go
Hi,
This PR adds mysql_transaction_isolation metric.
```
mysql_transaction_isolation{level="REPEATABLE-READ"} 1
````
=> Add mysql_transaction_isolation metric

mysqld-mixin/alerts/galera.yaml
There are 2 `MySQLReplicationLag` alerts.  I think it's just a typo.
=> mixin: fix redundant alert

mysqld_exporter.go
@SuperQ 
Fix a bug where the `tlsCfg.InsecureSkipVerify` flag was only consumed when using mTLS.
=> Allow tlsCfg.InsecureSkipVerify outside of mTLS

mysqld_exporter.go, mysqld_exporter_test.go
`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>
=> Remove ioutil

README.md
This fixes a code block that not properly closed, causing the next two sections rendered as code.
=> Fix unclosed code block in README.md

mysqld_exporter.go, mysqld_exporter_test.go
when using [filters](https://github.com/prometheus/mysqld_exporter#filtering-enabled-collectors), there would be a error
```
collected metric "mysql_exporter_collector_duration_seconds" { label:<name:"collector" value:"collect.perf_schema.replication_group_member_stats" > gauge:<value:0.001734619 > } was collected before with the same name and label values
```
the reason is that the collector is registed twice, I'll fix this error in the comming commits, this commit is about tests that can reproduce the error
=> fix duplicated collector when collectParams was passed in probe mode

README.md
Fix the type of params in Prometheus scrape_config
The old one is:
```
params:
auth_module: client.servers
```
It will introduce an issue that the Prometheus service fails to start, due to the config file error.
As in the official documents of Prometheus: [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config), `params` should be:
```
params:
[ <string>: [<string>, ...] ]
```
So, I updated the example to
```
params:
auth_module: [client.servers]
```
And the Prometheus service instance can start normally.
=> Fix prometheus scrape example in README.md

config/config.go, config/config_test.go, config/testdata/client_custom_tls.cnf
This PR is a modified version of the #674 to match the FormDSN supported by the #708.
Fixes: https://github.com/prometheus/mysqld_exporter/issues/673
=> Add MySQL TLS configurations

collector/exporter.go, collector/exporter_test.go, mysqld_exporter.go, probe.go
* mysql_exporter_scrapes_total 
* mysql_exporter_scrape_errors_total
* mysql_last_scrape_failed 
* mysql_exporter_collector_success (replace mysql_exporter_scrape_errors_total)
* mysql_up
* mysql_exporter_collector_success
* mysql_exporter_collector_duration_seconds
We are using mysqld_exporter in `multi-target` method, which means one exporter for multiple mysql instance, the crucial metric `mysql_up` must be isolated between requests, or there will be misunderstandings, some mysql instance would shown as down while in fact it is not.
all shared metrics are dropped especially `mysql_exporter_scrapes_total`  and `mysql_exporter_scrape_errors_total` , the metrics are useless since prometheus can record almost everything, including scrape fail for each collector.
`mysql_last_scrape_failed` …
=> Fix shared metrics between requests

collector/exporter.go
Use a return value on the scrape function to only send the `mysql_up` metric down the channel once.
=> Refactor mysql_up metric

collector/info_schema_innodb_metrics.go
The query introduced with #523 performs poorly when there are sufficient numbers of rows in `information_schema.columns`.
* Added using the `table_schema` as a filter
* Added limit to the query
=> Fix infoSchemaInnodbMetricsEnabledColumnQuery

config/config.go, config/config_test.go
This pull request expands the multi-target scraping ability introduced by #504 and #651 to UNIX domain sockets.
If the `target` query starts with `unix://`, connect to the server using UNIX domain socket. Otherwise, use TCP.
~This PR adds a new query parameter `network` to specify the network type either "tcp" or "unix". If no value is set, it defaults to "tcp".~
Support for multiple UNIX domain sockets is useful if, for example, mysqld_exporter runs on Cloud Run configured with multiple Cloud SQL connections. Cloud Run mounts multiple UNIX domain sockets on the `/cloudsql` directory. https://cloud.google.com/sql/docs/mysql/connect-run?hl=en#connect_to
(Fixed in #714) ~By the way, I found that the `/probe` endpoint emits error messages to the client along with metrics in some error …
=> Add UNIX domain socket support for multi-target scraping

collector/exporter.go
In the latest version, mysql_exporter has been support multiTarget feature.   
In this scene, while scraper.Scrape has a error, it's hard to locate the problem target.  So I add the target info in the error log.
=> feat: log Target  while error

collector/sys_user_summary.go
I just needed these new metrics, so now I'm using using 0.15.0-rc.0  with our db servers.
However our latencies in production db didn't fit to the uint64, so I changed them to float64.
Other fields can still can contain values that are too large, but I didn't change them because we're not going to hit them.
Thanks for your work. and use pull request in any way you see suitable.
```
user                statements     statement_latency  table_scans     file_ios      file_io_latency  current_connections  total_connections  unique_hosts  current_memory  total_memory_allocated
----------------  ------------  --------------------  -----------  -----------  -------------------  -------------------  -----------------  ------------  --------------  ----------------------
importer …
```
=> BUGFIX for 0.15.0-rc.0  sys.X$user_summary latencies doesn't fit to uint64 

mysqld_exporter.go
When I configured mysqld_exporter for multi targets as per the main README:
> To use the multi-target functionality, send an http request to the endpoint /probe?target=foo:3306 where target is set to the DSN of the MySQL instance to scrape metrics from.
If you use this - regardless of the target it uses 127.0.0.1 as the MySQL host. If you use the mysqld.addressflag - then for all targets it uses the mysqld.address host. 
Signed-off-by: Nick Knight <nick@babblevoice.com>
=> Use target in DSN builder.

collector/info_schema_auto_increment.go
=> issue-#725: use STRAIGHT_JOIN in infoSchemaAutoIncrementQuery

CHANGELOG.md, README.md, mysqld_exporter.go
Use a relative file as the default for the .my.cnf style configuration.
Fixes: https://github.com/prometheus/mysqld_exporter/issues/633
=> Don't use HOME env in the my-cnf config

README.md
It looks like the old link is dead/nonfunctional. This fixes it.
=> fix(docs): Update docker registry link in README.md

collector/slave_hosts.go, collector/slave_status.go
In MySQL 8.4, several "Replication SQL syntax" commands have been deprecated, requiring the use of new syntax. During testing, it was confirmed that errors occur with the old syntax. This PR updates the code to be compatible with the new syntax. Could you please review this PR?
The changes address the syntax errors that arise due to the deprecated commands. Below are the specific errors encountered:
```
mysqld-exporter  | ts=2024-05-15T02:39:40.760Z caller=exporter.go:173 level=error msg="Error from scraper" scraper=slave_status target=mysql_replica:3306 err="Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SLAVE STATUS' at line 1"
mysqld-exporter  | ts=2024-05-15T02:43:26.471Z …
```
=> Support MySQL 8.4 replicas syntax

collector/perf_schema_events_statements.go
The `perf_schema.eventsstatements` collector was incorrectly exposing "tmp_tables" as "tmp_disk_tables" and vice versa, due to query result being scanned in incorrect order.
Closes #849
=> Fix fetching tmpTables vs tmpDiskTables from performance_schema

collector/perf_schema_events_statements.go
Extend the query on `events_statements_summary_by_digest` to fetch `SUM_LOCK_TIME` and `SUM_CPU_TIME` and return them as counters. These are useful to report time spent running on the cpu (e.g. to sort results or run computations) vs waiting on locks (e.g. to acquire write lock on a table or row), by query digest.
=> Fetch lock time and cpu time from performance schema

collector/info_schema_innodb_sys_tablespaces.go, collector/info_schema_innodb_sys_tablespaces_test.go
- To be able to scrape the information_schema.innodb_sys_tablespaces tables
- MariaDB has [cleaned up the INFORMATION_SCHEMA.INNODB_ tables](https://jira.mariadb.org/browse/MDEV-19940) from version 10.5 on
Fixes:
- https://github.com/prometheus/mysqld_exporter/issues/528
- https://github.com/prometheus/mysqld_exporter/issues/662
Co-authored-by @businessbean 
Supersedes:
- https://github.com/prometheus/mysqld_exporter/pull/724
=> Skip SPACE_TYPE column for MariaDB >=10.5

README.md
@SuperQ 
When running docker run as currently specified in the README, it returns -bash: --config.my-cnf=./my.cnf: No such file or directory. If you try using .my.cnf as suggested by someone else in the issue #790 , it returns -bash: --config.my-cnf=.my.cnf: command not found.
It would be better to revise the documentation to have users create the cnf file themselves and use volume mounting instead of using an option.
The updated command is as follows:
```bash
docker run -d \
-p 9104:9104 \
-v /home/user/user_my.cnf:/.my.cnf \
--network my-mysql-network \
prom/mysqld-exporter
```
=> Fix Docker run command and update documentation for cnf file handling

collector/collector.go
👋 @SuperQ
After rotating some certificates last week, `mysql_global_status_ssl_server_not_after` metric stopped working. It turned out that the new certificates had expiration dates like `Jun  3 14:02:39 2024 GMT` (single digit day, non-zero padded) and parsing it returned ~negative results.~ (sorry, it was the end of a long day and while trying to be concise I mixed up some early testing results with the real behavior) an error:
```
parsing time "Jun  3 14:02:39 2024 GMT" as "Jan 02 15:04:05 2006 MST": cannot parse "3 14:02:39 2024 GMT" as "02"
```
=> Fixed parsing of timestamps with non-zero padded days

collector/info_schema_auto_increment.go
Hello, we have encountered the following issues in our actual production:
There are two tables in the database, test.x and test.X, which caused data collection failure.
Original error message:
```
An error has occurred while serving metrics:
4 error(s) occurred:
* collected metric "mysql_info_schema_auto_increment_column" { label:<name:"column" value:"id" > label:<name:"schema" value:"test" > label:<name:"table" value:"x" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "mysql_info_schema_auto_increment_column_max" { label:<name:"column" value:"id" > label:<name:"schema" value:"test" > label:<name:"table" value:"x" > gauge:<value:4.294967295e+09 > } was collected before with the same name and label values
* collected metric …
```
=>  Fix auto_increment metric collection errors caused by using collation in INFORMATION_SCHEMA searches

config/config.go
Calling ReloadConfig was not thread safe in spite of the mutex.  One thread could overwrite the package level cfg pointer after it was mutated by another thread.
=> Fix race condition in ReloadConfig

collector/info_schema_processlist.go
Otherwise `Error 1055: 'information_schema.processlist.HOST' isn't in GROUP BY` is raised.
fixes #610 (for details see [#issuecomment-1320577266](https://github.com/prometheus/mysqld_exporter/issues/610#issuecomment-1320577266))
@SuperQ 
CC @peterloeffler
=> Change processlist query to support ONLY_FULL_GROUP_BY sql_mode

collector/perf_schema_replication_applier_status_by_worker.go
The query in the replication_applier_status_by_worker check assumes the replication_applier_status_by_worker table layout in mysql 8.0.
Without this if you enable replication_applier_status_by_worker you'll receive the following error:
```
caller=exporter.go:174 level=error msg="Error from scraper" scraper=perf_schema.replication_applier_status_by_worker err="Error 1054: Unknown column 'LAST_APPLIED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP' in 'field list'
```
=> replication_applier_status_by_worker requires mysql 8.0

CHANGELOG.md
Changes:
* [CHANGE] Replace logging library go-kit/log with slog https://github.com/prometheus/mysqld_exporter/pull/875
* [FEATURE] Support for prometheus scrape timeout in probe endpoint https://github.com/prometheus/mysqld_exporter/pull/828
* [ENHANCEMENT] Support MySQL 8.4 replicas syntax https://github.com/prometheus/mysqld_exporter/pull/837
* [ENHANCEMENT] Fetch lock time and cpu time from performance schema https://github.com/prometheus/mysqld_exporter/pull/862
* [ENHANCEMENT] Add the instance struct to handle connections https://github.com/prometheus/mysqld_exporter/pull/859
* [ENHANCEMENT] Optimize code by using built-in constants in the standard lib https://github.com/prometheus/mysqld_exporter/pull/844
* [BUGFIX] Fix fetching tmpTables vs tmpDiskTables from performance_schema …
=> Release 0.16.0

collector/perf_schema_events_statements.go
This change appends the 3 quantile columns exposed in the `events_statements_summary_by_digest` table to the
`perf_schema_events_statements` collector so that they are available as a summary metric.
We believe this to be a useful addition so that the various quantiles (p95, p99, p99.5) are available to query and spot changes in performance for a given query. Our use case is to visualise these quantiles for a specific digest to provide more insight than just average query times.
The new summary metric `mysql_perf_schema_events_statements_latency` has 3 quantiles: 95, 99, 99.5 and in addition has a `sum` and `count` metric that matches the values of `events_statements_seconds_total` and `events_statements_total` respectively. These metrics may be considered redundant with this addition. …
=> Add perf_schema quantile columns to collector

mysqld-mixin/dashboards/mysql-overview.json
This was reported by the mixtool lint:
mixtool lint mixin.libsonnet
[uneditable-dashboard] 'MySQL': Dashboard 'MySQL' is editable, it should be set to 'editable: false'
This is quick attempt at fixing the mixin CI error going by its error description. I haven't looked further on the implications of this.
=> Update Mixin dashboard to editable: false

README.md
This must be a typo in the README only.
There is no other occurence when doing `git grep locahost` for this value.
=> Fix typo for locahost

collector/info_schema_tables.go
In `collector/info_schema_tables.go`, the SQL it uses to retrieves the table meta data is
```
SELECT
TABLE_SCHEMA,
...
FROM information_schema.tables
WHERE TABLE_SCHEMA = '%s'
```
Which could cause a problem if the schema contains the single quote character `'` (It's indeed a vaild character in database/table name), we should use the placeholder `?` and pass the schema as an argument to `db.QueryContext(...)` to avoid this kind of problem. Also to avoid the SQL injection problem as user can pass anything to `--collect.info_schema.tables.databases` in reality (accidentally or on purpose).
=> Fix database quoting problem in collector 'info_schema.tables'

collector/collector_test.go, collector/perf_schema_events_statements.go, collector/perf_schema_events_statements_test.go
Fix issue introduced in https://github.com/prometheus/mysqld_exporter/pull/862
Only query SUM_LOCK_TIME and SUM_CPU_TIME when using MySQL >= 8.0.28.
Fixes https://github.com/prometheus/mysqld_exporter/issues/905
=> Fix #905: use SUM_LOCK_TIME and SUM_CPU_TIME with mysql >= 8.0.28

README.md
Addresses issue 815:
https://github.com/prometheus/mysqld_exporter/issues/815
Like the author of the issue, I also used the example in the README file to setup scraping with Prometheus only to discover that by default the /metrics end-point is scraped instead.
=> Add missing metrics_path to multi-target example

collector/perf_schema_events_statements.go, collector/perf_schema_events_statements_test.go
Followup of https://github.com/prometheus/mysqld_exporter/pull/916, where I wrongly deleted query params formatting.
=> Fix query on perf_schema.events_statements_summary_by_digest

collector/perf_schema_events_statements.go, collector/perf_schema_events_statements_test.go
Followup of #916 and #920. These columns are not available in MariaDB.
=> Use QUANTILE columns only with mysql >= 8.0.28

collector/engine_innodb.go, collector/global_variables.go
Move regex vars to package level to avoid re-compilation on each scrape.
=> Review regex declarations in innodb and global variables collectors

config/config.go
Fixes #933 
Fixes #930 
Fixed the problem that password verification failed when there is a # symbol in the MySQL password (msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'USER'@'...' (using password: YES)")
=> Fixed the issue of authentication failure when the password contains the # symbol

collector/slave_status.go, collector/slave_status_test.go
This pull request adds support for parsing `Gtid_IO_Pos` and `Gtid_Slave_Pos` in the output of slave status.
The sequence number of GTID is the value of metric and domain_id and server_id are additional labels.
=> Add support for MariaDB GTID in slave status
