- mysqld_exporter.go
Depends on https://github.com/prometheus/log/pull/3
> Migrate logging to prometheus/log.

- CHANGELOG.md
- Makefile
Bump version and add a changelog.
> Cut release 0.2.0

- mysqld_exporter.go
In order to make it easier to differentiate between `SHOW SLAVE STATUS`
and `SHOW GLOBAL STATUS` we need add a `Subsystem` to metric names.
Refactor `SHOW GLOBAL STATUS` pattern matching
This will make room in the metric namespace for MySQL metrics from the
`performance_schema` tables.
> Refactor metrics

- mysqld_exporter.go
Add support for getting table metrics from MySQL
`performance_schema.table_io_waits_summary_by_table`
> Add support for performance_schema

- mysqld_exporter.go
Remove unecssary metrics:
* COUNT_READ is the same as COUNT_FETCH
* COUNT_WRITE is the same as COUNT_INSERT + COUNT_UPDATE + COUNT_DELETE
> Remove COUNT_{READ,WRITE}

- mysqld_exporter.go
Add more metrics from performance_schema:
* Time metrics for table_io_waits_summary_by_table
* Counter metrics for table_io_waits_summary_by_index_usage
* Time metrics for table_io_waits_summary_by_index_usage
Time metrics are returned by MySQL as `BIGINT` picoseconds, convert to
Float64 seconds.
Index usage columns are special[0].  Reads are counted for all indexs.
Writes are counted only for the `INDEX_NAME` with a value of `NULL`.
Bug fix: cleanup output column vars in perfSchemaTableWaitsRows.
[0]: http://dev.mysql.com/doc/refman/5.6/en/table-waits-summary-tables.html#table-io-waits-summary-by-index-usage-table
> Add new metrics

- mysqld_exporter.go
Add metrics for reporting the current value of auto_increment columns
Based on the reporting query:
https://github.com/SuperQ/bk-tools/blob/master/pk-full-ratio.sql
> Add auto_increment column metrics

- mysqld_exporter.go
SHOW GLOBAL VARIABLES provides gauge-like views of various MySQL
internal tunable settings.  These can be used for expressions that
compare current status (mysql_global_status_connections /
mysql_global_variables_max_connections)
> Add SHOW GLOBAL VARIABLES metris

- CHANGELOG.md
- README.md
Includes many PRs:
* https://github.com/prometheus/mysqld_exporter/pull/10
* https://github.com/prometheus/mysqld_exporter/pull/12
* https://github.com/prometheus/mysqld_exporter/pull/14
* https://github.com/prometheus/mysqld_exporter/pull/15
* https://github.com/prometheus/mysqld_exporter/pull/17
* https://github.com/prometheus/mysqld_exporter/pull/19
* https://github.com/prometheus/mysqld_exporter/pull/20
* https://github.com/prometheus/mysqld_exporter/pull/21
* https://github.com/prometheus/mysqld_exporter/pull/22
* https://github.com/prometheus/mysqld_exporter/pull/25
> Cut 0.3.0 release

- mysqld_exporter.go
Break up the giant scrape method.
Do the error handling a bit less repetitive.
I also had some initial attempts on unit testing in my branch, but that didn't go far yet.
@SuperQ
> General refactoring.

- mysqld_exporter.go
Don't collecting metrics that have not been used recently.
* Default to 1 day.
* Fix query string formatting.
> Limit events_statements to recently used

- mysqld_exporter.go
Fix[0] lost in refactoring[1].
[0]: https://github.com/prometheus/mysqld_exporter/commit/dbad3dcf71d5eb6a659aaacf4fb86253b9da15a5
[1]: https://github.com/prometheus/mysqld_exporter/commit/58de609465439a1074306db1299cad7dcec0c23c#diff-7f3e92469561ad831b3efc026d4ffcddR875
> Re-apply userStatData fix

- mysqld_exporter.go
> Add query schema mapping metric

- CHANGELOG.md
- Makefile
> Cut release 0.4.0

- Makefile.COMMON
- README.md
> Document new flag and add example

- mysqld_exporter.go
Update performance_schema table output values to be unsinged int.
> Performance Schema values are uint

- mysqld_exporter.go
Add a constant for manipulating picoseconds into seconds
> Correct picosecond math

- CHANGELOG.md
- Makefile
> Cut release 0.5.0

- mysqld_exporter.go
* sort merge passes - lots of merge passes can indicate too small a
sort_buffer_size
* sort rows - total number of rows sorted, useful for finding expensive
statements
* no index used - statements that cause full table scans
> Add additional events statements metrics

- mysqld_exporter.go
Add a session log_slow_filter[0] to avoid slow query logging of scrapes.
* Add a flag, default false, because this is not supported by Oracle MySQL.
[0]: https://www.percona.com/doc/percona-server/5.6/diagnostics/slow_extended.html
> Avoid slow query logging

- mysqld_exporter.go
Leverage lock-free `SHOW SLAVE STATUS` by choosing the right suffix on the first run and than using it on the next queries.
[Percona Server 5.5] (https://www.percona.com/doc/percona-server/5.5/reliability/show_slave_status_nolock.html) supports non-blocking `SHOW SLAVE STATUS NOLOCK`.
[Percona Server 5.6] (https://www.percona.com/doc/percona-server/5.6/reliability/show_slave_status_nolock.html) supports non-blocking `SHOW SLAVE STATUS NOLOCK` as well as `SHOW SLAVE STATUS NONBLOCKING` to match initial MySQL 5.7.
[Oracle MySQL 5.7] (http://dev.mysql.com/doc/refman/5.7/en/show-slave-status.html) initially supported `SHOW SLAVE STATUS NONBLOCKING`. As of 5.7.6 they removed the suffix due to locking changes and it became unnecessary.
> Leverage lock-free SHOW SLAVE STATUS

- README.md
Update the README:
* Add missing flags
* Add version compatibility column
* Split out collector and general flags
> Update flag documentation

- mysqld_exporter.go
Looks like we need the tests and CI 🙂
> Fixed uint for scrapeInnodbMetrics() and gofmt

- mysqld_exporter.go
Add a flag for controlling the minimum time that a thread must be in a
specific state in order to be counted.
This allows for detection of threads "stuck" in a specific state for a
minimum period of time.  This avoids counting short-lived thread state
chagnes from polluting the metrics.
> Add minimum time flag for processlist metrics

- mysqld_exporter.go
Instead of aborting the collection when a single collector fails, record
an error and continue.
> Soft error on collector failure

- CHANGELOG.md
- Makefile
> Update CHANGELOG for 0.7.1 release

- README.md
Thanks Ben for adding Travis integration :beer:
> Linked build status icon

- mysqld_exporter.go
Collect the total time for each processlist state in addition to the
count of threads in each state.
> Collect time metrics for processlist

- mysqld_exporter.go
- mysqld_exporter_test.go
Split out SHOW GLOBAL STATUS metrics named like `Innodb_buffer_pool_pages_.*`.
* `data`, `dirty`, `free`, `misc` are current state gauges.
* The rest are counters.
> Separate innodb_buffer_pool_pages status metrics

- .travis.yml
- collector/collector.go
- collector/collector_test.go
- collector/global_status.go
- collector/global_status_test.go
- mysqld_exporter.go
- mysqld_exporter_test.go
Move `GLOBAL STATUS` scraper to a separate file.
> Refactor collectors

- collector/binlog.go
- collector/engine_tokudb.go
- collector/engine_tokudb_test.go
- collector/global_variables.go
- collector/slave_status.go
- mysqld_exporter.go
- mysqld_exporter_test.go
* Move scrapeEngineTokudbStatus to collector package.
* Move scrapeBinlogSize to collector package.
* Move scrapeSlaveStatus to collector package.
* Move scrapeGlobalVariables to collector package.
> Move More Collectors

- collector/collector.go
- collector/perf_schema.go
- collector/perf_schema_events_statements.go
- collector/perf_schema_events_waits.go
- collector/perf_schema_file_events.go
- collector/perf_schema_index_io_waits.go
- collector/perf_schema_index_io_waits_test.go
- collector/perf_schema_table_io_waits.go
- collector/perf_schema_table_lock_waits.go
- mysqld_exporter.go
- mysqld_exporter_test.go
* Cleanup unused bits in mysqld_exporter.go main.
> Move perf_schema to collector package

- collector/info_schema_innodb_sys_tablespaces.go
- collector/info_schema_innodb_sys_tablespaces_test.go
- mysqld_exporter.go
Implment colection of InnoDB tablespace metrics from
`information_schema.innodb_sys_tablespaces`
> Add collector for innodb_sys_tablespaces

- CHANGELOG.md
- Makefile
* Update Makefile
* Update CHANGELOG
> Release v0.8.0

- README.md
- example.rules
Add some basic recording and alerting rules.
> Add an example recording rules file

- collector/global_status_test.go
> Add test for wsrep_cluster_status = "Primary"

- mysqld_exporter.go
Add a last collector durations.
* Remove obsolete total duration metric.
Closes: https://github.com/prometheus/mysqld_exporter/issues/188
> Add collector duration metrics

- .travis.yml
- CONTRIBUTING.md
- Makefile
- collector/exporter_test.go
- docker-compose.yml
> Add Docker Compose for integration tests

- collector/info_schema_innodb_cmp_test.go
- collector/info_schema_innodb_cmpmem_test.go
> Cleanup codespell issues.

- example.rules
Signed-off-by: James Turnbull <james@lovedthanlost.net>
> Updated rules for Prometheus 2.0

- vendor/github.com/go-sql-driver/mysql/AUTHORS
- vendor/github.com/go-sql-driver/mysql/CHANGELOG.md
- vendor/github.com/go-sql-driver/mysql/README.md
- vendor/github.com/go-sql-driver/mysql/appengine.go
- vendor/github.com/go-sql-driver/mysql/auth.go
- vendor/github.com/go-sql-driver/mysql/buffer.go
- vendor/github.com/go-sql-driver/mysql/collations.go
- vendor/github.com/go-sql-driver/mysql/connection.go
- vendor/github.com/go-sql-driver/mysql/connection_go18.go
- vendor/github.com/go-sql-driver/mysql/const.go
- vendor/github.com/go-sql-driver/mysql/driver.go
- vendor/github.com/go-sql-driver/mysql/dsn.go
- vendor/github.com/go-sql-driver/mysql/errors.go
- vendor/github.com/go-sql-driver/mysql/fields.go
- vendor/github.com/go-sql-driver/mysql/infile.go
- vendor/github.com/go-sql-driver/mysql/packets.go
- vendor/github.com/go-sql-driver/mysql/rows.go
- vendor/github.com/go-sql-driver/mysql/statement.go
- vendor/github.com/go-sql-driver/mysql/transaction.go
- vendor/github.com/go-sql-driver/mysql/utils.go
- vendor/github.com/go-sql-driver/mysql/utils_go17.go
- vendor/github.com/go-sql-driver/mysql/utils_go18.go
- vendor/google.golang.org/appengine/LICENSE
- vendor/google.golang.org/appengine/cloudsql/cloudsql.go
- vendor/google.golang.org/appengine/cloudsql/cloudsql_classic.go
- vendor/google.golang.org/appengine/cloudsql/cloudsql_vm.go
- vendor/vendor.json
* Update github.com/go-sql-driver/mysql to 1.4.0 to support MySQL 8.
* We should be able to finally merge https://github.com/prometheus/mysqld_exporter/pull/210 after that.
> Update github.com/go-sql-driver/mysql to 1.4.0 to support MySQL 8.

- example.rules.yml
This is just a conversion of the rules file using promtool upgrade example.rules so when someone is reading from the github they don't have to convert it themselves.
> [Add] Prometheus 2.0 Supported Rules

- .circleci/config.yml
- CHANGELOG.md
- collector/global_status.go
- collector/global_status_test.go
Hello.
This PR adds wsrep_evs_repl_latency metric collecting.
Closes: #309
>  Add wsrep_evs_repl_latency metric

- CHANGELOG.md
- collector/collector.go
- collector/info_schema_processlist.go
- collector/mysql.go
- collector/mysql_user.go
- mysqld_exporter.go
It's a follow up of pull request #341
> Add scraping of mysql.user

- vendor/github.com/go-sql-driver/mysql/CHANGELOG.md
- vendor/github.com/go-sql-driver/mysql/auth.go
- vendor/github.com/go-sql-driver/mysql/connection_go18.go
- vendor/github.com/go-sql-driver/mysql/driver.go
- vendor/github.com/go-sql-driver/mysql/packets.go
- vendor/github.com/go-sql-driver/mysql/utils.go
- vendor/vendor.json
Updated go-sql-driver/mysql. Automated tests and a short manual test look good.
I am not a go programmer so i would appreciate a quick sanity check before merging. 
Thanks!
Closes: https://github.com/prometheus/mysqld_exporter/issues/345
> Update to go-sql-driver/mysql 1.4.1

- .circleci/config.yml
- .travis.yml
- go.mod
- go.sum
- vendor/github.com/jtolds/gls/stack_tags.go
- vendor/modules.txt
> Update to Go 1.12

- collector/binlog.go
Mysql 8.x returns 3 columns during `SHOW BINARY LOGS` query instead of 2 in older mysql.
It fixes https://github.com/prometheus/mysqld_exporter/issues/413
It's based on @SuperQ comment in https://github.com/prometheus/mysqld_exporter/pull/390
> fix binlog metrics on mysql 8.x

- README.md
my-mysql-network is the wrong placeholder. This should be the hostname as in the Build section at the top
> Change my-mysql-network placeholder to hostname

- README.md
- collector/exporter.go
Signed-off-by: bergquist <carl.bergquist@gmail.com>
> Make timeout duration unit more explicit

- README.md
- go.mod
- go.sum
- mysqld_exporter.go
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Add TLS and basic authentication

- mysqld_exporter.go
> Wrong name in msg

- mysqld-mixin/alerts/galera.yaml
- mysqld-mixin/alerts/general.yaml
- mysqld-mixin/dashboards/mysql-overview.json
Update various items to make the mixin linter happy.
Signed-off-by: SuperQ <superq@gmail.com>
> Fixup mixin linting

- config/config.go
Use driver's format method, `FormatDSN()`, instead of manually constructing DSN.
> using mysql.Config.FormatDSN() in FormDSN()

- probe.go
This PR addresses #663 and the problem I mentioned in the description of #707.
Currently (8fa4a07777dd26bc29afb26c1ecdfc3c68ca9f69), the `/probe` endpoint emits both error messages and metrics if one of the following situations is met.
- config file does not contain the section which is requested by the `auth_module` parameter.
- network address which is requested by the `target` parameter is ill-formed.
```
Error parsing config section [non-existent]
mysql_exporter_last_scrape_error 1
mysql_exporter_scrapes_total 1
mysql_up 0
probe_success 0
```
This PR removes metrics to emit only a single line of the error message.
It also removes `probe_success` metrics introduced in 593b0095a5bd0bd852029dd2dfa5f204a15de946 (not yet released) for the following reasons:
- It will always be 1 (in case …
> Fix a mixture of error messages and metrics is returned from the multiple target endpoint.

- README.md
- collector/sys.go
- collector/sys_user_summary.go
- collector/sys_user_summary_test.go
- mysqld_exporter.go
Behavior is controlled by a relevant flag and defaults to False.
This addresses feature request https://github.com/prometheus/mysqld_exporter/issues/627
> Add support for collecting metrics from sys.user_summary

- .circleci/config.yml
- .golangci.yml
- config/config.go
Switch from using codespell to misspell.
> Switch spell check to golangci-lint

- .circleci/config.yml
- .github/workflows/golangci-lint.yml
- .promu.yml
> Update Go version
